### ISSUE TITLE
Workflows duplicates on pull request

### ISSUE THREAD

**Issue by foo2810** [foo2810/ad-hoc-vimconfig#17]
On pull request, both push and pull request event are triggered.
Duplicate workflow execution is wasteful.

**Comment by foo2810** [comment]
**Root cause**

During opening pull request at source branch of devel branch, when new commits are pushed, both push and pull_request events are triggered.
The `synchronize` event is main cause.

```yaml
on:
  push:
    branches: ["main", "devel"]
  pull_request:
    branches: [ "*" ]
    types: ["opened", "synchronize", "reopened"]
```

So, redefining new workflow of pull_request event for devel branches, the problem should be resolved.
